export const transactionsData = [
  {
    id: 1,
    amount: "4500",
    type: "income",
    date: "09/04/2022",
    concept: "Honorarios",
  },
  {
    id: 2,
    amount: "300",
    type: "expenditure",
    date: "09/04/2022",
    concept: "Cena en restaurant",
    category: "Comida",
  },
  {
    id: 3,
    amount: "1300",
    type: "expenditure",
    date: "02/04/2022",
    concept: "Cuota del club",
    category: "Ocio",
  },
  {
    id: 4,
    amount: "1100",
    type: "expenditure",
    date: "01/04/2022",
    concept: "Pago de servicios del hogar",
    category: "Servicios",
  },
  {
    id: 5,
    amount: "500",
    type: "income",
    date: "29/03/2022",
    concept: "Cobro por venta",
  },
  {
    id: 6,
    amount: "4300",
    type: "expenditure",
    date: "29/03/2022",
    concept: "Alquiler del departamento",
    category: "Alquiler",
  },
  {
    id: 7,
    amount: "14500",
    type: "income",
    date: "20/03/2022",
    concept: "Sueldo",
  },
  {
    id: 8,
    amount: "3000",
    type: "expenditure",
    date: "19/03/2022",
    concept: "Compra supermercado",
    category: "Comida",
  },
  {
    id: 9,
    amount: "13200",
    type: "income",
    date: "15/03/2022",
    concept: "Sueldo",
  },
  {
    id: 10,
    amount: "2500",
    type: "income",
    date: "12/03/2022",
    concept: "Prestamo",
  },
];

export const categories = [
  "Alquiler",
  "Comida",
  "Cuotas",
  "Expensas",
  "Impuestos",
  "Ocio",
  "Seguros",
  "Servicios",
];
